CREATE TABLE edi_schemas
(
    segment_id      char(3) NOT NULL,
    data_index      smallint NOT NULL,
    data_element_id smallint,
    name            character varying,
    required        char(1),
    comments        text,
    PRIMARY KEY (segment_id, data_index)
);

ALTER TABLE edi_schemas ADD CONSTRAINT edi_schemas_data_element_id_fk
    FOREIGN KEY (data_element_id) REFERENCES edi_data_elements (id);

-- This data is not comprehensive.
INSERT INTO edi_schemas (segment_id, data_index, data_element_id, name, required)
VALUES
('AK1', 0, null, 'Functional Group Response Header', ),
('AK1', 1, 479, 'Functional Identifier Code', 'M'),
('AK1', 2, 28, 'Group Control Number', 'M'),
('AK1', 3, 480, 'Version / Release / Industry Identifier Code', 'O'),
('AK2', 0, null, 'Transaction Set Response Header', ),
('AK2', 1, 143, 'Transaction Set Identifier Code', 'M'),
('AK2', 2, 329, 'Transaction Set Control Number', 'M'),
('AK2', 3, 1705, 'Implementation Convention Reference', 'X'),
('AK3', 0, null, 'Data Segment Note', ),
('AK3', 1, 721, 'Segment ID Code', 'M'),
('AK3', 2, 719, 'Segment position in transaction set', 'M'),
('AK3', 3, 447, 'Loop Identifier Code', 'O'),
('AK3', 4, 720, 'Segment Syntax Error Code', 'O'),
('AK3', 5, 720, 'Segment Syntax Error Code', 'O'),
('AK3', 6, 720, 'Segment Syntax Error Code', 'O'),
('AK3', 7, 720, 'Segment Syntax Error Code', 'O'),
('AK3', 8, 720, 'Segment Syntax Error Code', 'O'),
('AK4', -101, 722, 'Element Position in Segment', 'M'),
('AK4', -102, 1528, 'Component Data Element Position in Composite', 'O'),
('AK4', -103, 1686, 'Data Element Reference Number', 'O'),
('AK4', 0, null, 'Data Element Note', ),
('AK4', 1, -1030, 'Position in segment', 'M'),
('AK4', 2, 725, 'Data element reference number', 'O'),
('AK4', 3, 723, 'Data element syntax error code', 'M'),
('AK4', 4, 724, 'Copy of bad data element', 'O'),
('AK5', 0, null, 'Transaction Set Response Trailer', ),
('AK5', 1, 717, 'Transaction Set Acknowledgment Code', 'M'),
('AK5', 2, 718, 'Transaction Set Syntax Error Code', 'O'),
('AK5', 3, 718, 'Transaction Set Syntax Error Code', 'O'),
('AK5', 4, 718, 'Transaction Set Syntax Error Code', 'O'),
('AK5', 5, 718, 'Transaction Set Syntax Error Code', 'O'),
('AK5', 6, 718, 'Transaction Set Syntax Error Code', 'O'),
('AK9', 0, null, 'Functional Group Response Trailer', ),
('AK9', 1, 715, 'Functional Group Acknowledge Code', 'M'),
('AK9', 2, 97, 'Number of transaction sets included', 'M'),
('AK9', 3, 123, 'Number of received transaction sets', 'M'),
('AK9', 4, 2, 'Number of accepted transaction sets', 'M'),
('AK9', 5, 716, 'Functional Group Syntax Error Code', 'O'),
('AK9', 6, 716, 'Functional Group Syntax Error Code', 'O'),
('AK9', 7, 716, 'Functional Group Syntax Error Code', 'O'),
('AK9', 8, 716, 'Functional Group Syntax Error Code', 'O'),
('AK9', 9, 716, 'Functional Group Syntax Error Code', 'O'),
('AT5', 0, null, 'Bill of Lading Handling Requirements', ),
('AT5', 1, 152, 'Special Handling Code', 'X'),
('AT5', 2, 560, 'Special Services Code', 'X'),
('AT5', 3, 153, 'Special Handling Description', 'X'),
('AT7', 0, null, 'Shipment Status Details', ),
('AT7', 1, 1650, 'Shipment Status Code', 'X'),
('AT7', 2, 1651, 'Shipment Status or Appointment Reason Code', 'X'),
('AT7', 3, 1652, 'Shipment/Appointment Status Code', 'X'),
('AT7', 4, 1651, 'Shipment Status or Appointment Reason Code', 'X'),
('AT7', 5, 373, 'Status Date', 'X'),
('AT7', 6, 337, 'Status Time', 'X'),
('AT7', 7, 623, 'Time Code', 'X'),
('AT8', 0, null, 'Shipment Weight, Packing and Quantity Data', ),
('AT8', 1, 187, 'Weight Qualifier', 'X'),
('AT8', 2, 188, 'Weight Unit Code', 'X'),
('AT8', 3, 81, 'Weight', 'X'),
('AT8', 4, 80, 'Lading Quantity', 'O'),
('AT8', 5, 80, 'Lading Quantity', 'O'),
('AT8', 6, 184, 'Volume Unit Qualifier', 'X'),
('AT8', 7, 183, 'Volume', 'X'),
('B1', 0, null, 'Beginning Segment for Booking or Pick-up/Delivery', ),
('B1', 1, 140, 'SCAC - Standard Carrier Alpha Code', 'M'),
('B1', 2, 145, 'Shipment Identification Number', 'M'),
('B1', 3, 373, 'Date', 'O'),
('B1', 4, 558, 'Reservation Action Code', 'M'),
('B1', 5, 1073, 'Yes/No Condition or Response Code', 'M'),
('B1', 6, 1658, 'Shipment or Work Assignment Decline Reason Code', 'X'),
('B10', 0, null, 'Beginning Segment for Transportation Carrier Shipment Status Message', ),
('B10', 1, 127, 'Reference Identification', 'M'),
('B10', 2, 145, 'Shipment Identification Number', 'M'),
('B10', 3, 140, 'SCAC - Standard Carrier Alpha Code', 'M'),
('B10', 4, 71, 'Inquiry Request Number', 'X'),
('B10', 5, 128, 'Reference Identification Qualifier', 'X'),
('B10', 6, 127, 'Reference Identification', 'X'),
('B10', 7, 1073, 'Yes/No Condition or Response Code', 'X'),
('B10', 8, 373, 'Date', 'M'),
('B10', 9, 337, 'Time', 'M'),
('B2', 0, null, 'Beginning Segment for Shipment Information', ),
('B2', 1, 375, 'Tariff Service Code', 'X'),
('B2', 2, 140, 'SCAC (Standard Carrier Alpha Code)', 'M'),
('B2', 3, 154, 'Standard Point Location Code', 'X'),
('B2', 4, 145, 'Shipment Identification Number', 'M'),
('B2', 5, 188, 'Weight Unit Code', 'X'),
('B2', 6, 146, 'Shipment Method of Payment', 'M'),
('B2', 7, 147, 'Shipment Qualifier', 'X'),
('B2', 8, 86, 'Total Equipment', 'X'),
('B2', 9, 460, 'Shipment Weight Code', 'X'),
('B2', 10, 501, 'Customs Documentation Handling Code', 'X'),
('B2', 11, 335, 'Transportation Terms Code', 'X'),
('B2', 12, 591, 'Payment Method Code', 'X'),
('B2A', 0, null, 'Set Purpose', ),
('B2A', 1, 353, 'Transaction Set Purpose Code', 'M'),
('B2A', 2, 346, 'Application Type', 'O'),
('B3', 0, null, 'Beginning Segment for Carrier''s Invoice', ),
('B3', 1, 147, 'Shipment Qualifier', 'O'),
('B3', 2, 76, 'Invoice Number', 'M'),
('B3', 3, 145, 'Shipment Identification Number', 'M'),
('B3', 4, 146, 'Shipment Method of Payment', 'M'),
('B3', 5, 188, 'Weight Unit Code', 'O'),
('B3', 6, 373, 'Date', 'M'),
('B3', 7, 193, 'Net Amount Due', 'M'),
('B3', 8, 202, 'Correction Indicator', 'O'),
('B3', 9, 32, 'Delivery Date', 'M'),
('B3', 10, 374, 'Date/Time Qualifier', 'M'),
('B3', 11, 140, 'SCAC - Standard Carrier Alpha Code', 'M'),
('B3', 12, 373, 'Date', 'O'),
('C2', 0, null, 'Bank ID', ),
('C2', 1, 8, 'Bank Client Code', 'M'),
('C2', 2, 66, 'Identification Code Qualifier', 'M'),
('C2', 3, 67, 'Identification Code', 'M'),
('C3', 0, null, 'Currency', ),
('C3', 1, 100, 'Currency Code', 'M'),
('C3', 2, 280, 'Exchange Rate', 'O'),
('C3', 3, 100, 'Currency Code', 'O'),
('C3', 4, 100, 'Currency Code', 'O'),
('G61', 0, null, 'Contact', ),
('G61', 1, 366, 'Contact Function Code', 'M'),
('G61', 2, 93, 'Name', 'M'),
('G61', 3, 365, 'Communication Number Qualifier', 'O'),
('G61', 4, 364, 'Contact Inquiry Reference', 'O'),
('G61', 5, 443, 'Contact Inquiry Reference', 'X'),
('G62', 0, null, 'Date/Time', ),
('G62', 1, 432, 'Date Qualifier', 'X'),
('G62', 2, 373, 'Date', 'X'),
('G62', 3, 176, 'Time Qualifier', 'X'),
('G62', 4, 337, 'Time', 'X'),
('G62', 5, 623, 'Time Code', 'O'),
('GE', 0, null, 'Functional Group Trailer', ),
('GE', 1, 97, 'Number of Transaction Sets Included', 'M'),
('GE', 2, 28, 'Group Control Number', 'M'),
('GS', 0, null, 'Functional Group Header', ),
('GS', 1, 479, 'Functional Identifier Code', 'M'),
('GS', 2, 142, 'Application Sender''s Code', 'M'),
('GS', 3, 124, 'Application Receiver''s Code', 'M'),
('GS', 4, 373, 'Date', 'M'),
('GS', 5, 337, 'Time', 'M'),
('GS', 6, 28, 'Group Control Number', 'M'),
('GS', 7, 455, 'Responsible Ageny Code', 'M'),
('GS', 8, 480, 'Version / Release / Industry Identifier Code', 'M'),
('H1', 0, null, 'Hazardous Material', ),
('H1', 1, 62, 'Hazardous Material Code', 'M'),
('H1', 2, 209, 'Hazardous Material Class Code', 'O'),
('H1', 3, 208, 'Hazardous Material Code Qualifier', 'O'),
('H3', 0, null, 'Special Handling Instructions', ),
('H3', 2, 153, 'Special Handling Description', 'X'),
('IEA', 0, null, 'Interchange Control Trailer', ),
('IEA', 1, -16, 'Number of Included Functional Groups', 'M'),
('IEA', 2, -12, 'Interchange Control Number', 'M'),
('ISA', 0, null, 'Interchange Control Header', ),
('ISA', 1, -1, 'Authorization Information Qualifier', 'M'),
('ISA', 2, -2, 'Authorization Information', 'M'),
('ISA', 3, -3, 'Security Information Qualifier', 'M'),
('ISA', 4, -4, 'Security Information', 'M'),
('ISA', 5, -5, 'Interchange ID Qualifier', 'M'),
('ISA', 6, -6, 'Interchange Sender ID', 'M'),
('ISA', 7, -5, 'Interchange ID Qualifier', 'M'),
('ISA', 8, -7, 'Interchange Receiver ID', 'M'),
('ISA', 9, -8, 'Date', 'M'),
('ISA', 10, -9, 'Time', 'M'),
('ISA', 11, -10, 'Repetition Separator or EDI standard identifier', 'M'),
('ISA', 12, -11, 'Interchange Control Version Number', 'M'),
('ISA', 13, -12, 'Interchange Control Number', 'M'),
('ISA', 14, -13, 'Acknowledgment Requested', 'M'),
('ISA', 15, -14, 'Usage Indicator', 'M'),
('ISA', 16, -15, 'Composite Delimiter / Component Terminator', 'M'),
('K1', 0, null, 'Remarks', ),
('K1', 1, 61, 'Free-form Information', 'M'),
('K1', 2, 61, 'Free-form Information', 'O'),
('L0', 0, null, 'Line Item - Quantity and Weight', ),
('L0', 1, 213, 'Lading Line Item Number', 'O'),
('L0', 2, 220, 'Billed/Rated-as Quantity', 'X'),
('L0', 3, 221, 'Billed/Rated-as Qualifier', 'X'),
('L0', 4, 81, 'Weight', 'X'),
('L0', 5, 187, 'Weight Qualifier', 'X'),
('L0', 6, 183, 'Volume', 'X'),
('L0', 7, 184, 'Volume Unit Qualifier', 'X'),
('L0', 8, 80, 'Lading Quantity', 'X'),
('L0', 9, 211, 'Packaging Form Code', 'X'),
('L0', 11, 188, 'Weight Unit Code', 'O'),
('L1', 0, null, 'Rate and Charges', ),
('L1', 1, 213, 'Lading Line Item Number', 'O'),
('L1', 2, 60, 'Freight Rate', 'X'),
('L1', 3, 122, 'Rate/Value Qualifier', 'X'),
('L1', 4, 58, 'Charge', 'X'),
('L1', 8, 150, 'Special Charge or Allowance Code', 'O'),
('L1', 9, 121, 'Rate Class Code', 'O'),
('L1', 12, 276, 'Special Charge Description', 'O'),
('L1', 13, 257, 'Tariff Application Code', 'O'),
('L1', 14, 74, 'Declared Value', 'X'),
('L1', 17, 220, 'Billed/Rated-as Quantity', 'C'),
('L1', 18, 221, 'Billed/Rated-as Qualifier', 'C'),
('L1', 20, 100, 'Currency Code', 'O'),
('L11', 0, null, 'Business Instructions and Reference Number', ),
('L11', 1, 127, 'Reference Identification', 'X'),
('L11', 2, 128, 'Reference Identification Qualifier', 'X'),
('L11', 3, 352, 'Description', 'X'),
('L11', 4, 373, 'Date', 'O'),
('L11', 5, 1073, 'Yes/No Condition or Response Code', 'O'),
('L3', 0, null, 'Total Weight and Charges', ),
('L3', 1, 81, 'Weight', 'X'),
('L3', 2, 187, 'Weight Qualifier', 'X'),
('L3', 3, 60, 'Freight Rate', 'X'),
('L3', 4, 122, 'Rate / Value Qualifier', 'X'),
('L3', 5, 58, 'Charge', 'O'),
('L3', 6, 191, 'Advances', 'O'),
('L3', 7, 117, 'Prepaid Amount', 'O'),
('L3', 8, 150, 'Special Charge or Allowance Code', 'O'),
('L3', 9, 183, 'Volume', 'X'),
('L3', 10, 184, 'Volume Unit Qualifier', 'X'),
('L3', 11, 80, 'Lading Quantity', 'O'),
('L3', 12, 188, 'Weight Unit Code', 'O'),
('L3', 13, 171, 'Tariff Number', 'O'),
('L3', 14, 74, 'Declared Value', 'X'),
('L3', 15, 122, 'Rate / Value Qualifier', 'X'),
('L4', 0, null, 'Measurement', ),
('L4', 1, 82, 'Length', 'M'),
('L4', 2, 189, 'Width', 'M'),
('L4', 3, 65, 'Height', 'M'),
('L4', 4, 90, 'Measurement Unit Qualifier', 'M'),
('L4', 5, 380, 'Quantity', 'X'),
('L4', 6, 1271, 'Industry Code', 'X'),
('L5', 0, null, 'Description, Marks, and Numbers', ),
('L5', 1, 213, 'Lading Line Item Number', 'O'),
('L5', 2, 79, 'Lading Description', 'O'),
('L5', 3, 22, 'Commodity Code', 'X'),
('L5', 4, 23, 'Commodity Code Qualifier', 'X'),
('L5', 5, 103, 'Packaging Code', 'O'),
('L5', 6, 87, 'Marks and Numbers', 'X'),
('L5', 7, 88, 'Marks and Numbers Qualifier', 'O'),
('L5', 8, 23, 'Commodity Code Qualifier', 'X'),
('L5', 9, 22, 'Commodity Code', 'X'),
('L5', 10, 595, 'Compartment ID Code', 'O'),
('L7', 0, null, 'Tariff Reference', ),
('L7', 1, 213, 'Lading Line Item Number', 'O'),
('L7', 2, 168, 'Tariff Agency Code', 'O'),
('L7', 3, 171, 'Tariff Number', 'O'),
('L7', 7, 59, 'Freight Class Code', 'O'),
('L7', 10, 373, 'Effective Date', 'O'),
('L7', 13, 294, 'Tariff Distance', 'O'),
('L7', 14, 295, 'Distance Qualifier', 'O'),
('L7', 15, 19, 'City Name', 'O'),
('L7', 16, 156, 'State or Province Code', 'O'),
('L9', 0, null, 'Charge Detail', ),
('L9', 1, 150, 'Special Charge or Allowance Code', 'M'),
('L9', 2, 782, 'Monetary Amount', 'M'),
('LAD', 0, null, 'Lading Detail', ),
('LAD', 1, 211, 'Packaging Form Code', 'X'),
('LAD', 2, 80, 'Lading Quantity', 'X'),
('LAD', 3, 188, 'Weight Unit Code', 'X'),
('LAD', 4, 395, 'Unit Weight', 'X'),
('LAD', 5, 188, 'Weight Unit Code', 'X'),
('LAD', 6, 81, 'Weight', 'X'),
('LAD', 7, 235, 'Product/Service ID Qualifier', 'X'),
('LAD', 8, 234, 'Product/Service ID', 'X'),
('LAD', 9, 235, 'Product/Service ID Qualifier', 'X'),
('LAD', 10, 234, 'Product/Service ID', 'X'),
('LAD', 11, 235, 'Product/Service ID Qualifier', 'X'),
('LAD', 12, 234, 'Product/Service ID', 'X'),
('LAD', 13, 79, 'Lading Description', 'X'),
('LEP', 0, null, 'EPA Required Data', ),
('LEP', 1, 806, 'EPA Waste Stream Number Code', 'O'),
('LEP', 2, 807, 'Waste Characteristics Code', 'O'),
('LEP', 3, 156, 'State or Province Code', 'X'),
('LEP', 4, 127, 'Reference Identification', 'X'),
('LFH', 0, null, 'Freeform Hazardous Material Information', ),
('LFH', 1, 808, 'Hazardous Material Shipment Information Qualifier', 'M'),
('LFH', 2, 809, 'Hazardous Material Shipment Information', 'M'),
('LFH', 3, 809, 'Hazardous Material Shipment Information', 'O'),
('LFH', 4, 1023, 'Hazard Zone Code', 'O'),
('LFH', 5, 355, 'Unit or Basis for Measurement Code', 'X'),
('LFH', 6, 380, 'Quantity', 'X'),
('LFH', 7, 380, 'Quantity', 'O'),
('LH1', 0, null, 'Hazardous Identification Information', ),
('LH1', 1, 355, 'Unit or Basis for Measurement Code', 'M'),
('LH1', 2, 80, 'Lading Quantity', 'M'),
('LH1', 3, 277, 'UN/NA Identification Code', 'O'),
('LH1', 4, 200, 'Hazardous Materials Page', 'O'),
('LH1', 5, 22, 'Commodity Code', 'O'),
('LH1', 6, 355, 'Unit or Basis for Measurement Code', 'O'),
('LH1', 7, 380, 'Quantity', 'O'),
('LH1', 8, 595, 'Compartment ID Code', 'O'),
('LH1', 9, 665, 'Residue Indicator Code', 'O'),
('LH1', 10, 254, 'Packing Group Code', 'O'),
('LH1', 11, 1375, 'Interim Hazardous Material Regulatory Number', 'O'),
('LH2', 0, null, 'Hazardous Classification Information', ),
('LH2', 1, 215, 'Hazardous Classification', 'O'),
('LH2', 2, 983, 'Hazardous Class Qualifier', 'O'),
('LH2', 3, 218, 'Hazardous Placard Notation', 'O'),
('LH2', 4, 222, 'Hazardous Endorsement', 'O'),
('LH2', 5, 759, 'Reportable Quantity Code', 'O'),
('LH2', 6, 355, 'Unit or Basis for Measurement Code', 'X'),
('LH2', 7, 408, 'Temperature', 'X'),
('LH2', 8, 355, 'Unit or Basis for Measurement Code', 'X'),
('LH2', 9, 408, 'Temperature', 'X'),
('LH2', 10, 355, 'Unit or Basis for Measurement Code', 'X'),
('LH2', 11, 408, 'Temperature', 'X'),
('LH3', 0, null, 'Hazardous Material Shipping Name', ),
('LH3', 1, 224, 'Hazardous Material Shipping Name', 'X'),
('LH3', 2, 984, 'Hazardous Material Shipping Name Qualifier', 'X'),
('LH3', 3, 985, 'N.O.S. Indicator Code', 'O'),
('LH3', 4, 1073, 'Yes/No Condition or Response Code', 'O'),
('LH4', 0, null, 'Canadian Dangerous Requirements', ),
('LH4', 1, 238, 'Emergency Response Plan Number', 'O'),
('LH4', 2, 364, 'Communication Number', 'O'),
('LH4', 3, 254, 'Packing Group Code', 'O'),
('LH4', 4, 230, 'Subsidiary Classification', 'O'),
('LH4', 5, 230, 'Subsidiary Classification', 'O'),
('LH4', 6, 230, 'Subsidiary Classification', 'O'),
('LH4', 7, 271, 'Subsidiary Risk Indicator', 'O'),
('LH4', 8, 267, 'Net Explosive Quantity', 'X'),
('LH4', 9, 805, 'Canadian Hazardous Notation', 'O'),
('LH4', 10, 986, 'Special Commodity Indicator Code', 'O'),
('LH4', 11, 364, 'Communication Number', 'O'),
('LH4', 12, 355, 'Unit or Basis for Measurement Code', 'X'),
('LH6', 0, null, 'Hazardous Certification', ),
('LH6', 1, 93, 'Name', 'O'),
('LH6', 2, 272, 'Hazardous Certification Code', 'X'),
('LH6', 3, 273, 'Hazardous Certification Declaration', 'X'),
('LH6', 4, 273, 'Hazardous Certification Declaration', 'O'),
('LHT', 0, null, 'Transborder Hazardous Requirements', ),
('LHT', 1, 215, 'Hazardous Classification', 'O'),
('LHT', 2, 218, 'Hazardous Placard Notation', 'O'),
('LHT', 3, 222, 'Hazardous Endorsement', 'O'),
('LX', 0, null, 'Transaction Set Line Number', ),
('LX', 1, 554, 'Assigned Number', 'M'),
('M7', 0, null, 'Seal Numbers', ),
('M7', 1, 225, 'Seal Number', 'M'),
('M7', 2, 225, 'Seal Number', 'O'),
('M7', 3, 225, 'Seal Number', 'O'),
('M7', 4, 225, 'Seal Number', 'O'),
('M7', 5, 98, 'Entity Identifier Code', 'O'),
('MAN', 0, null, 'Marks and Numbers', ),
('MAN', 1, 88, 'Marks and Numbers Qualifier', 'M'),
('MAN', 2, 87, 'Marks and Numbers', 'M'),
('MAN', 3, 87, 'Marks and Numbers', 'O'),
('MEA', -401, 355, 'Unit or Basis for Measurement Code', 'O'),
('MEA', -402, 1018, 'Exponent', 'O'),
('MEA', -403, 649, 'Multiplier', 'O'),
('MEA', -404, 355, 'Unit or Basis for Measurement Code', 'O'),
('MEA', -405, 1018, 'Exponent', 'O'),
('MEA', -406, 649, 'Multiplier', 'O'),
('MEA', -407, 355, 'Unit or Basis for Measurement Code', 'O'),
('MEA', -408, 1018, 'Exponent', 'O'),
('MEA', -409, 649, 'Multiplier', 'O'),
('MEA', -410, 355, 'Unit or Basis for Measurement Code', 'O'),
('MEA', -411, 1018, 'Exponent', 'O'),
('MEA', -412, 649, 'Multiplier', 'O'),
('MEA', -413, 355, 'Unit or Basis for Measurement Code', 'O'),
('MEA', -414, 1018, 'Exponent', 'O'),
('MEA', -415, 649, 'Multiplier', 'O'),
('MEA', 0, null, 'Measurements', ),
('MEA', 1, 737, 'Measurement Reference ID Code', 'O'),
('MEA', 2, 738, 'Measurement Qualifier', 'O'),
('MEA', 3, 739, 'Measurement Value', 'O'),
('MEA', 4, -1001, 'Composite Unit of Measure', 'O'),
('MEA', 5, 740, 'Range Minimum', 'X'),
('MEA', 6, 741, 'Range Maximum', 'X'),
('MEA', 7, 935, 'Measurement Significance Code', 'O'),
('MEA', 8, 936, 'Measurement Attribute Code', 'X'),
('MEA', 9, 752, 'Surface/Layer/Position Code', 'O'),
('MEA', 10, 1373, 'Measurement Method or Device', 'O'),
('MS1', 0, null, 'Equipment, Shipment, or Real Property Location', ),
('MS1', 1, 19, 'City Name', 'X'),
('MS1', 2, 156, 'State or Province Code', 'X'),
('MS1', 3, 26, 'Country Code', 'X'),
('MS1', 4, 1654, 'Longitude', 'X'),
('MS1', 5, 1655, 'Latitude', 'X'),
('MS1', 6, 1280, 'East/West', 'O'),
('MS1', 7, 1280, 'North/South', 'O'),
('MS2', 0, null, 'Equipment Location', ),
('MS2', 1, 140, 'SCAC - Standard Carrier Alpha Code', 'X'),
('MS2', 2, 207, 'Equipment Number', 'X'),
('MS2', 3, 40, 'Equipment Description Code', 'O'),
('MS2', 4, 761, 'Equipment Number Check Digit', 'O'),
('MS3', 0, null, 'Interline Information', ),
('MS3', 1, 140, 'SCAC - Standard Carrier Alpha Code', 'M'),
('MS3', 2, 133, 'Routing Sequence Code', 'M'),
('MS3', 3, 19, 'City', 'X'),
('MS3', 4, 91, 'Transportation Method/Type Code', 'O'),
('MS3', 5, 156, 'State or Province Code', 'O'),
('N1', 0, null, 'Name', ),
('N1', 1, 98, 'Entity Identifier Code', 'M'),
('N1', 2, 93, 'Name', 'M'),
('N1', 3, 66, 'Identification Code Qualifier', 'O'),
('N1', 4, 67, 'Identification Code', 'O'),
('N1', 5, 706, 'Entity Relationship Code', 'O'),
('N1', 6, 98, 'Entity Identifier Code', 'X'),
('N2', 0, null, 'Additional Name Information', ),
('N2', 1, 93, 'Name', 'M'),
('N2', 2, 93, 'Name', 'O'),
('N3', 0, null, 'Address Information', ),
('N3', 1, 166, 'Address Information', 'M'),
('N3', 2, 166, 'Address Information', 'O'),
('N4', 0, null, 'Geographic Location', ),
('N4', 1, 19, 'City', 'O'),
('N4', 2, 156, 'State / Province', 'O'),
('N4', 3, 116, 'Postal Code', 'O'),
('N4', 4, 26, 'Country Code', 'O'),
('N4', 5, 309, 'Location Qualifier', 'X'),
('N4', 6, 310, 'Location Identifier', 'O'),
('N4', 7, 1715, 'Country Subdivision Code', 'X'),
('N7', 0, null, 'Equipment Details', ),
('N7', 1, 206, 'Equipment Initial', 'O'),
('N7', 2, 207, 'Equipment Number', 'M'),
('N7', 3, 81, 'Weight', 'X'),
('N7', 4, 187, 'Weight Qualifier', 'X'),
('N7', 5, 167, 'Tare Weight', 'X'),
('N7', 6, 232, 'Weight Allowance', 'O'),
('N7', 7, 205, 'Dunnage', 'O'),
('N7', 8, 183, 'Volume', 'X'),
('N7', 9, 184, 'Volume Unit Qualifier', 'X'),
('N7', 10, 102, 'Ownership Code', 'O'),
('N7', 11, 40, 'Equipment Description Code', 'O'),
('N7', 12, 140, 'Standard Carrier Alpha Code', 'O'),
('N7', 13, 319, 'Temperature Control', 'O'),
('N7', 14, 219, 'Position', 'O'),
('N7', 15, 567, 'Equipment Length', 'O'),
('N7', 16, 571, 'Tare Qualifier Code', 'X'),
('N7', 17, 188, 'Weight Unit Code', 'O'),
('N7', 18, 761, 'Equipment Number Check Digit', 'O'),
('N7', 19, 56, 'Type of Service Code', 'O'),
('N7', 20, 65, 'Height', 'O'),
('N7', 21, 189, 'Width', 'O'),
('N7', 22, 24, 'Equipment Type', 'O'),
('N7', 23, 140, 'Standard Carrier Alpha Code', 'O'),
('N7', 24, 301, 'Car Type Code', 'O'),
('N7A', 0, null, 'Accessorial Equipment Details', ),
('N7A', 1, 1042, 'Load or Device Code', 'O'),
('N7A', 2, 82, 'Length', 'O'),
('N7A', 3, 1043, 'Diameter', 'O'),
('N7A', 4, 1044, 'Hose Type Code', 'O'),
('N7A', 5, 1043, 'Diameter', 'O'),
('N7A', 6, 1043, 'Diameter', 'O'),
('N7A', 7, 1045, 'Inlet or Outlet Material Type Code', 'O'),
('N7A', 8, 1046, 'Inlet or Outlet Fitting Type Code', 'O'),
('N7A', 9, 1047, 'Miscellaneous Equipment Code', 'O'),
('N7B', 0, null, 'Additional Equipment Details', ),
('N7B', 1, 1024, 'Number of Tank Compartments', 'O'),
('N7B', 2, 1025, 'Loading or Discharge Location Code', 'O'),
('N7B', 3, 1026, 'Vessel Material Code', 'O'),
('N7B', 4, 1030, 'Gasket Type Code', 'O'),
('N7B', 5, 1031, 'Trailer Lining Type Code', 'O'),
('N7B', 6, 127, 'Reference Identification', 'O'),
('N9', -701, 128, 'Reference Identification Qualifier', 'M'),
('N9', -702, 127, 'Reference Identification', 'M'),
('N9', -703, 128, 'Reference Identification Qualifier', 'X'),
('N9', -704, 127, 'Reference Identification', 'X'),
('N9', -705, 128, 'Reference Identification Qualifier', 'X'),
('N9', -706, 127, 'Reference Identification', 'X'),
('N9', 0, null, 'Reference Identification', ),
('N9', 1, 128, 'Reference Identification Qualifier', 'M'),
('N9', 2, 127, 'Reference Identification', 'X'),
('N9', 3, 369, 'Free-form Description', 'X'),
('N9', 4, 373, 'Date', 'O'),
('N9', 5, 337, 'Time', 'X'),
('N9', 6, 623, 'Time Code', 'O'),
('N9', 7, -1040, 'Reference Identifier', 'O'),
('NM1', 0, null, 'Individual or Organizational Name', ),
('NM1', 1, 98, 'Name Entity Identifier Code', 'M'),
('NM1', 2, 1065, 'Entity Type Qualifier', 'M'),
('NM1', 3, 1035, 'Last Name or Organizational Name', 'O'),
('NM1', 4, 1036, 'First Name', 'O'),
('NTE', 0, null, 'Notes / Special Instructions', ),
('NTE', 1, 363, 'Note Reference Code', 'O'),
('NTE', 2, 352, 'Description', 'M'),
('OID', 0, null, 'Order Identification Detail', ),
('OID', 1, 127, 'Reference Identification', 'X'),
('OID', 2, 324, 'Purchase Order Number', 'X'),
('OID', 3, 127, 'Reference Identification', '0'),
('OID', 4, 355, 'Unit or Basis for Measurement Code', 'X'),
('OID', 5, 380, 'Quantity', 'X'),
('OID', 6, 188, 'Weight Unit Code', 'X'),
('OID', 7, 81, 'Weight', 'X'),
('OID', 8, 184, 'Volume Unit Qualifier', 'X'),
('OID', 9, 183, 'Volume', 'X'),
('PLD', 0, null, 'Pallet Information', ),
('PLD', 1, 406, 'Quantity of Pallets Shipped', 'M'),
('PLD', 2, 399, 'Pallet Exchange Code', 'O'),
('PLD', 3, 188, 'Weight Unit Code', 'X'),
('PLD', 4, 81, 'Weight', 'X'),
('POD', 0, null, 'Proof of Delivery', ),
('POD', 1, 373, 'Date', 'M'),
('POD', 2, 337, 'Time', 'C'),
('POD', 3, 93, 'Name', 'C'),
('PRF', 0, null, 'Purchase Order Reference', ),
('PRF', 1, 324, 'Purchase Order Number', 'M'),
('PRF', 4, 373, 'Date', 'M'),
('Q7', 0, null, 'Lading Exception Code', ),
('Q7', 1, 33, 'Lading Exception Code', 'M'),
('Q7', 2, 211, 'Packaging Form Code', 'O'),
('Q7', 3, 80, 'Lading Quantity', 'X'),
('R3', 0, null, 'Route Information - Motor', ),
('R3', 1, 140, 'SCAC - Standard Carrier Alpha Code', 'M'),
('R3', 2, 133, 'Routing Sequence Code', 'M'),
('R3', 3, 19, 'City Name', 'O'),
('R3', 4, 91, 'Transportation Method/Type Code', 'O'),
('R3', 5, 154, 'Standard Point Location Code', 'O'),
('R3', 6, 76, 'Invoice Number', 'O'),
('R3', 9, 369, 'Free-form Description', 'O'),
('R3', 10, 284, 'Service Level Code', 'X'),
('R3', 11, 284, 'Service Level Code', 'X'),
('S5', 0, null, 'Stop Off Details', ),
('S5', 1, 165, 'Stop Sequence Number', 'M'),
('S5', 2, 163, 'Stop Reason Code', 'M'),
('S5', 3, 81, 'Weight', 'X'),
('S5', 4, 188, 'Weight Unit Code', 'X'),
('S5', 5, 382, 'Number of Units Shipped', 'X'),
('S5', 6, 355, 'Unit or Basis for Measurement Code', 'X'),
('S5', 7, 183, 'Volume', 'X'),
('S5', 8, 184, 'Volume Unit Qualifier', 'X'),
('S5', 9, 352, 'Description', 'O'),
('S5', 10, 154, 'Standard Point Location Code', 'O'),
('S5', 11, 190, 'Accomplish Code', 'O'),
('SE', 0, null, 'Transaction End', ),
('SE', 1, 96, 'Number of Segments', 'M'),
('SE', 2, 329, 'Transaction Set Control Number', 'M'),
('SPO', 0, null, 'Shipment Purchase Order Detail', ),
('SPO', 1, 324, 'Purchase Order Number', 'M'),
('SPO', 3, 355, 'Unit or Basis for Measurement Code', 'X'),
('SPO', 4, 380, 'Quantity', 'X'),
('SPO', 5, 188, 'Weight Unit Code', 'X'),
('SPO', 6, 81, 'Weight', 'X'),
('SPO', 7, 647, 'Application Error Condition Code', 'O'),
('SPO', 8, 127, 'Reference Identification', 'O'),
('ST', 0, null, 'Transaction Set Start', ),
('ST', 1, 143, 'Transaction Set Identifier Code', 'M'),
('ST', 2, 329, 'Transaction Set Control Number', 'M'),
('ST', 3, 1705, 'Implementation Convention Reference', 'X'),
('V9', 0, null, 'Event Detail', 'O'),
('V9', 1, 304, 'Event Code', 'M'),
('V9', 8, 641, 'Status Reason Code', 'O')
ON CONFLICT DO NOTHING;
